### ISSUE TITLE
Missing Dependency Information - MS Visual C++ 2015?

### ISSUE THREAD

**Issue by bbrandt** [datalust/clef-tool#22]
I am getting an error about being unable to load 'api-ms-win-core-console-l2-1-0.dll' after installing and running clef.  Presumably, this is because I don't have the Visual C++ 2015 runtime installed.  

I have the MS VC++2017 Redist installed.  I thought this was supposed to be [binary compatible](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017) with the VC++ 2015 redist, but have not yet tested with MS VC++ 2015 to verify that's the issue.
![image](https://user-images.githubusercontent.com/602767/33099457-8bcfa4ee-ced6-11e7-9333-36f89318302b.png)

I'm thinking that compiling clef in .NET core 2.0 [might fix](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x) this as well.

```
>"C:\Program Files\CLEF Tool\c
lef" -i myapp-20171121.jsonl
2017-11-21T22:02:59.2556254Z Caught exception while emitting to sink Serilog.Sin
ks.Literate.LiterateConsoleSink: System.DllNotFoundException: Unable to load DLL
 'api-ms-win-core-console-l2-1-0.dll': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetConsoleScreenBufferInfo(IntPtr hConsoleOutput, CONSOLE_
SCREEN_BUFFER_INFO& lpConsoleScreenBufferInfo)
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeed
ed)
   at System.ConsolePal.ResetColor()
   at Serilog.Sinks.Literate.LiterateConsoleSink.Emit(LogEvent logEvent)
```

**Comment by nblumhardt** [comment]
Interesting - thanks for the report 👍 

I don't have 2015, but I do have 2013 along with 2017...

![image](https://user-images.githubusercontent.com/342712/33100098-ea5d05be-cf5e-11e7-9319-b91d124e1b47.png)

It may be that you're not on Win 10 ... https://github.com/datalust/clef-tool/blob/dev/src/Datalust.ClefTool/Datalust.ClefTool.csproj#L6 ... how's my guess? :-)

**Comment by bbrandt** [comment]
That is totally it!  I'm on Win7.    :-)

**Comment by nblumhardt** [comment]
https://github.com/datalust/seqcli/blob/dev/src/SeqCli/SeqCli.csproj#L7 is using the new, generic `win-x64` RID; we should switch to that here, too, I think.
