### ISSUE TITLE
Error processing @seqid

### ISSUE THREAD

**Issue by kevinmcfarlane** [datalust/clef-tool#23]
I generated a json file from your new Seq.App.JsonArchive. This created data like

..."@i":"4fab5bbf","@seqid":"event-10ca0520dbd908d34b09000000000000","Name":...

When I ran clef on this to produce a text file output I got this error...

**`@seqid` on line 1 are unrecognized.**

Removing @seqid: from the input file allows clef to run.

**Comment by nblumhardt** [comment]
Thank you for the report, Kevin. It looks like we need to update the version of _Serilog.Formatting.Compact.Reader_ used by this package. I'll take a look ASAP.

Best regards,
Nick

**Comment by nblumhardt** [comment]
@kevinmcfarlane 1.0.43 was just published, this issue should be fixed there: https://github.com/datalust/clef-tool/releases/tag/v1.0.43 - please let us know if you hit any further issues. Thanks again!

**Comment by kevinmcfarlane** [comment]
Thanks Nick. That works. 

(Btw the msi was initially blocked by Windows Defender SmartScreen, but the previous one wasn't. Odd.}

**Comment by nblumhardt** [comment]
Thanks for the heads-up. We need to update the build to use our code signing cert - it takes Windows Defender a while to start trusting the binaries, otherwise :+1:
