### ISSUE TITLE
JSON properties cannot be used in format-template

### ISSUE THREAD

**Issue by ChristoWolf** [datalust/clef-tool#28]
Hi!

It is not possible to output JSON properties inside structured logging objects.
Using your example
`{"@t":"2016-06-07T03:44:57.8532799Z","@mt":"Hello, {@User}","User":{"Name":"nblumhardt","Tags":[1,2,3]}}`,
it is possible to navigate to e.g. User.Name with 
`--filter="User.Name = 'nblumhardt'"`.
However, it is not possible to extract the property using
`--format-template="{User.Name}{NewLine}"`. I would expect the output to show the value here, but it just shows
`User.Name`.
I am using Clef-tool 1.0.43.0 on Windows 10, did not try it out with any other versions.
Also, I noticed that outputting a JSON values via templates destroys JSON validity (e.g. when the JSON contains booleans, they are capitalized; spacing is changed).

**Comment by nblumhardt** [comment]
Hi! Thanks for the notes.

RE the JSON point, you need to use the `:j` format specifier in output templates to use JSON formatting for values - the default is the original .NET/Serilog format.

The lack of support for `User.Name` is inherited from Serilog's output templates; we've considered writing an alternative templating engine for this but so far haven't yet found the opportunity.

Hope this helps,
Nick

**Comment by ChristoWolf** [comment]
Thanks for the quick reply and the helpful information!
Unfortunately, I tried to use `:j` to format my value (which is a valid JSON) before too, but the format stays the same. In any case, I found that I still cannot use this as a workaround for my extraction issue.
Regarding the custom template engine: That would be very useful! Should I leave this issue open as a reminder for this (as it is the original purpose of the issue)?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. If `:j` isn't working for you, I'll take a look into it; would it be possible to provide an example of the input data, and `clef-tool` command-line?

You might try `seqcli print` in the meantime, it's a more recent incarnation of this functionality and that subcommand doesn't have any specific dependencies on Seq.

**Comment by ChristoWolf** [comment]
Sorry for the delayed follow-up.
I cannot share my exact example, but it should be easily reproducible with your original JSON in the OP by additionally adding some boolean JSON entry in the User object and formatting with template or :j.

**Comment by ChristoWolf** [comment]
Hi @nblumhardt!
Are there any news regarding this?
If not, I can offer to take a look.

**Comment by nblumhardt** [comment]
Hi @ChristoWolf! Thanks for the nudge - hope you've had a good ..... wow, that's been a year! :-)

> The lack of support for User.Name is inherited from Serilog's output templates; we've considered writing an alternative templating engine for this but so far haven't yet found the opportunity.

Good news, this templating engine now exists - https://github.com/serilog/serilog-expressions/#formatting-with-expressiontemplate

The syntax is slightly different from what `clef-tool` uses today, but actually based on CLEF, so a much more natural fit for this tool. Timestamps are called `@t`, etc.

This project isn't frequently updated, so you may need to tinker with the publishing, but I would be keen to support a "v2" based on _Serilog.Expressions_ rather than _Serilog.Filters.Expressions_, if you are open to giving it a shot!
