### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jods4** [datalust/clef-tool#29]
Are you still maintaining this tool? It's very handy.

The last release is 2 years old.

I would like some improvements like supporting `{Properties}` in output.

According to this comment it was just waiting on Serilog 2.5 to get this feature:
https://github.com/datalust/clef-tool/blob/7e85044c3ca9215e41ed48bbb61031f03bce25d9/src/Datalust.ClefTool/Cli/Commands/PipeCommand.cs#L28

Now Serilog is at 2.9 and there has not been a new release since.

**Comment by nblumhardt** [comment]
Hi! Yes, we're happy making releases. I'll try to get one through the pipeline today, with some dependency updates :+1:

Functionally, we've been considering the project "done" for now, though with some more free time we'd ideally extend support to macOS and Linux. PRs are welcome if there's anything you'd especially like to see; I'll close this once I'm sure CI is happy and we've got a new binary into `/releases`.

**Comment by nblumhardt** [comment]
Should be good to go, now! https://github.com/datalust/clef-tool/releases/tag/v1.0.47

**Comment by jods4** [comment]
Yeah, I'm not really looking for new features, just seeing `{Properties}` is important to me.
Also I use the `tail -f` trick to monitor live logs on a console and it works fine.

Did something go wrong with the build?
I installed the .msi and there's no executable inside it anymore (`clef.dll`).
I'm sure I can run this with `dotnet run` but it's not really convenient for command line usage.

**Comment by nblumhardt** [comment]
Oh, sorry, looks like in switching from the early netcoreapp1.1 target to 3.1, the version on the launcher executable has gone backwards, which doesn't go well with Windows Installer. The binary is in there, you will need to uninstall and reinstall to fix it.

I think we're best off dropping MSI for this project, and just distributing zips for the target platforms (as we do in https://github.com/datalust/seqcli).

**Comment by jods4** [comment]
OK thanks, running the installer again (Repair) fixed it!
Would be fine with just a zip.
