### ISSUE TITLE
WinGet Installer

### ISSUE THREAD

**Issue by tiksn** [datalust/clef-tool#35]
This is an amazing tool. However, it would be great to have WinGet installer for quick install and use from the command line.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! We're not planning any additional work on this codebase right at the moment, but we'll keep this in the backlog :+1:

Most of our recent effort is going into `seqcli`, which includes all of the functionality of this tool via the `print` and `ingest` commands.

If it's an option, it's easy to run via Docker with:

```
cat log.clef | docker run --rm -it datalust/seqcli print  --filter="Version > 100"
```

Let me know if this helps!
Nick

**Comment by tiksn** [comment]
actually, I am using clef-tool to import into SEQ, so if I can do it with seqcli it is even better ))

thanks for quick reply.

should I close the issue then?

**Comment by nblumhardt** [comment]
Thanks, that's great :+1:
