### ISSUE TITLE
Add clef-tool to Chocolatey and Homebrew

### ISSUE THREAD

**Issue by Cheesebaron** [datalust/clef-tool#36]
Would be really cool if this tool could be signed and published to Chocolatey and Homebrew or alternatively as a dotnet tool.

Downloading and allowing all the files, especially on macOS is very cumbersome. However, when it works, this tool is excellent!

**Comment by nblumhardt** [comment]
Thanks for the suggestion, @Cheesebaron 👍 Currently, publishing as a `dotnet` tool would be the quickest/lowest-friction option to add 🤔
